/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.automobile;

import com.cyberbotics.webots.controller.Robot;

public class Car extends Driver {
  private transient long swigCPtr;

  protected Car(long cPtr, boolean cMemoryOwn) {
    super(automobileJNI.Car_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Car obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        automobileJNI.delete_Car(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Car() {
    this(automobileJNI.new_Car(), true);
  }

  public int getType() {
    return automobileJNI.Car_getType(swigCPtr, this);
  }

  public int getEngineType() {
    return automobileJNI.Car_getEngineType(swigCPtr, this);
  }

  public void setIndicatorPeriod(double period) {
    automobileJNI.Car_setIndicatorPeriod(swigCPtr, this, period);
  }

  public double getIndicatorPeriod() {
    return automobileJNI.Car_getIndicatorPeriod(swigCPtr, this);
  }

  public boolean getBackwardsLights() {
    return automobileJNI.Car_getBackwardsLights(swigCPtr, this);
  }

  public boolean getBrakeLights() {
    return automobileJNI.Car_getBrakeLights(swigCPtr, this);
  }

  public double getTrackFront() {
    return automobileJNI.Car_getTrackFront(swigCPtr, this);
  }

  public double getTrackRear() {
    return automobileJNI.Car_getTrackRear(swigCPtr, this);
  }

  public double getWheelbase() {
    return automobileJNI.Car_getWheelbase(swigCPtr, this);
  }

  public double getFrontWheelRadius() {
    return automobileJNI.Car_getFrontWheelRadius(swigCPtr, this);
  }

  public double getRearWheelRadius() {
    return automobileJNI.Car_getRearWheelRadius(swigCPtr, this);
  }

  public double getWheelEncoder(int wheel) {
    return automobileJNI.Car_getWheelEncoder(swigCPtr, this, wheel);
  }

  public double getWheelSpeed(int wheel) {
    return automobileJNI.Car_getWheelSpeed(swigCPtr, this, wheel);
  }

  public double getRightSteeringAngle() {
    return automobileJNI.Car_getRightSteeringAngle(swigCPtr, this);
  }

  public double getLeftSteeringAngle() {
    return automobileJNI.Car_getLeftSteeringAngle(swigCPtr, this);
  }

  public void enableLimitedSlipDifferential(boolean enable) {
    automobileJNI.Car_enableLimitedSlipDifferential(swigCPtr, this, enable);
  }

  public void enableIndicatorAutoDisabling(boolean enable) {
    automobileJNI.Car_enableIndicatorAutoDisabling(swigCPtr, this, enable);
  }

  public final static int TRACTION = 0;
  public final static int PROPULSION = 1;
  public final static int FOUR_BY_FOUR = 2;

  public final static int COMBUTSION_ENGINE = 0;
  public final static int ELECTRIC_ENGINE = 1;
  public final static int PARALLEL_HYBRID_ENGINE = 2;
  public final static int POWER_SPLIT_HYBRID_ENGINE = 3;

  public final static int WHEEL_FRONT_RIGHT = 0;
  public final static int WHEEL_FRONT_LEFT = 1;
  public final static int WHEEL_REAR_RIGHT = 2;
  public final static int WHEEL_REAR_LEFT = 3;
  public final static int WHEEL_NB = WHEEL_REAR_LEFT + 1;

}
